### ISSUE TITLE
Setup CI/CD Pipeline with Checks and Automatic NuGet Publishing

### ISSUE THREAD

**Issue by kiliczsh** [kiliczsh/instagram-nuget#2]
We need to set up a CI/CD pipeline to automate the building, testing, and publishing of the InstagramClient package. This pipeline should include checks to ensure code quality and successful builds before publishing the package to NuGet.

1.	Create a GitHub Actions workflow file to automate the build and test process.
2.	Add steps to the workflow to build the project and run unit tests.
3.	Add a step to publish the package to NuGet if all checks pass.
4.	Ensure the workflow includes triggers for pull requests and pushes to the main branch.
5.	Securely store the NuGet API key in GitHub Secrets.

✅ 
•	A GitHub Actions workflow is created and placed in the .github/workflows directory.
•	The workflow builds the project and runs unit tests.
•	The workflow publishes the package to NuGet upon successful checks.
•	The workflow is triggered on pull requests and pushes to the main branch.
•	The NuGet API key is securely stored and used in the workflow.

--- 

Workflow File (Not Final):
```yaml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --no-restore --verbosity normal

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Pack
        run: dotnet pack --configuration Release --no-restore

      - name: Publish to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key $NUGET_API_KEY
 ```
